<a href="https://colab.research.google.com/github/AnuBolishetty/Anubolishetty_INFO5731_Spring2026/blob/main/Bolishetty_Anu_Assignment_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 Assignment 1**

In this assignment, you will work on gathering text data from an open data source via web scraping or API. Following this, you will need to clean the text data and perform syntactic analysis on the data. Follow the instructions carefully and design well-structured Python programs to address each question.

**Expectations**:
*   Use the provided .*ipynb* document to write your code & respond to the questions. Avoid generating a new file.
*   Write complete answers and run all the cells before submission.
*   Make sure the submission is "clean"; *i.e.*, no unnecessary code cells.
*   Once finished, allow shared rights from top right corner (*see Canvas for details*).

* **Make sure to submit the cleaned data CSV in the comment section - 10 points**

**Total points**: 100


**Late Submission will have a penalty of 10% reduction for each day after the deadline.**

**Please check that the link you submitted can be opened and points to the correct assignment.**

# Question 1 (25 points)

Write a python program to collect text data from **either of the following sources** and save the data into a **csv file:**

(1) Collect all the customer reviews of a product (you can choose any porduct) on amazon. [atleast 1000 reviews]

(2) Collect the top 1000 User Reviews of a movie recently in 2024 or 2025 (you can choose any movie) from IMDB. [If one movie doesn't have sufficient reviews, collect reviews of atleast 2 or 3 movies]


(3) Collect the **abstracts** of the top 10000 research papers by using the query "machine learning", "data science", "artifical intelligence", or "information extraction" from Semantic Scholar.

(4) Collect all the information of the 904 narrators in the Densho Digital Repository.

(5)**Collect a total of 10000 reviews** of the top 100 most popular software from G2 and Capterra.

In [ ]:
!apt-get -qq update
!apt-get -qq install -y \
  libxcomposite1 libxdamage1 libxfixes3 libxrandr2 \
  libxkbcommon0 libxshmfence1 libx11-6 libx11-xcb1 libxcb1 \
  libxext6 libxi6 libxtst6 libxrender1 libxss1 \
  libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 \
  libcups2 libdrm2 libgbm1 libasound2 \
  libpangocairo-1.0-0 libpango-1.0-0 libgtk-3-0

!pip -q install -U playwright
!playwright install chromium

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../00-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../01-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../02-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../03-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../04-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Preparing to unpack .../05-libasound2_1.2.6.1-1ubuntu1.1_amd64.deb ...
Unpacking libasound2:amd64 (1.2.6.1-1ubuntu1.1) over (1.2.6.1-1ubuntu1) ...
Preparing to unpack .../06-libasound2-data_1.2.6.1-1ubuntu1.1_all.deb ...
Unpacking libasound2-data (1.2.6.1-1ubuntu1.1) over (1.2.6.1-1ubuntu1) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../07-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../08-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../09-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../10-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package libgtk-3-common.
Preparing to unpack .../11-libgtk-3-common_3.24.33-1ubuntu2.2_all.deb ...
Unpacking libgtk-3-common (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libgtk-3-0:amd64.
Preparing to unpack .../12-libgtk-3-0_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libgtk-3-bin.
Preparing to unpack .../13-libgtk-3-bin_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package librsvg2-common:amd64.
Preparing to unpack .../14-librsvg2-common_2.52.5+dfsg-3ubuntu0.2_amd64.deb ...
Unpacking librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libasound2-data (1.2.6.1-1ubuntu1.1) ...
Setting up librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up libasound2:amd64 (1.2.6.1-1ubuntu1.1) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up libgtk-3-common (3.24.33-1ubuntu2.2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.8+dfsg-1ubuntu0.4) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.7) ...
Setting up libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.11) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

Setting up libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Setting up at-spi2-core (2.44.0-3) ...
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 23.1 MB/s eta 0:00:00
Downloading Chrome for Testing 145.0.7632.6 (playwright chromium v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/linux64/chrome-linux64.zip
(node:1402) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
167.3 MiB [] 0% 340.0s167.3 MiB [] 0% 75.0s167.3 MiB [] 0% 39.8s167.3 MiB [] 0% 28.8s167.3 MiB [] 0% 21.8s167.3 MiB [] 0% 18.8s167.3 MiB [] 0% 13.6s167.3 MiB [] 1% 9.5s167.3 MiB [] 2% 6.7s167.3 MiB [] 2% 7.0s167.3 MiB [] 2% 6.8s167.3 MiB [] 4% 4.9s167.3 MiB [] 5% 4.2s167.3 MiB [] 5% 3.9s167.3 MiB [] 6% 3.5s167.3 MiB [] 7% 3.2s167.3 MiB [] 8% 3.1s167.3 MiB [] 9% 2.8s167.3 MiB [] 10% 2.7s167.3 MiB [] 11% 2.5s167.3 MiB [] 12% 2.5s167.3 MiB [] 13% 2.4s167.3 MiB [] 14% 2.3s167.3 MiB [] 15% 2.3s167.3 MiB [] 15% 2.4s167.3 MiB [] 16% 2.3s167.3 MiB [] 17% 2.3s167.3 MiB [] 18% 2.2s167.3 MiB [] 19% 2.2s167.3 MiB [] 20% 2.2s167.3 MiB [] 20% 2.1s167.3 MiB [] 21% 2.1s167.3 MiB [] 22% 2.1s167.3 MiB [] 23% 2.0s167.3 MiB [] 24% 2.0s167.3 MiB [] 25% 1.9s167.3 MiB [] 26% 1.8s167.3 MiB [] 28% 1.8s167.3 MiB [] 29% 1.7s167.3 MiB [] 30% 1.7s167.3 MiB [] 31% 1.6s167.3 MiB [] 32% 1.6s167.3 MiB [] 33% 1.6s167.3 MiB [] 34% 1.5s167.3 MiB [] 34% 1.6s167.3 MiB [] 35% 1.5s167.3 MiB [] 36% 1.5s167.3 MiB [] 37% 1.5s167.3 MiB [] 38% 1.4s167.3 MiB [] 39% 1.4s167.3 MiB [] 40% 1.4s167.3 MiB [] 41% 1.4s167.3 MiB [] 42% 1.3s167.3 MiB [] 43% 1.3s167.3 MiB [] 44% 1.3s167.3 MiB [] 45% 1.2s167.3 MiB [] 45% 1.3s167.3 MiB [] 46% 1.3s167.3 MiB [] 47% 1.3s167.3 MiB [] 47% 1.2s167.3 MiB [] 48% 1.2s167.3 MiB [] 49% 1.2s167.3 MiB [] 50% 1.1s167.3 MiB [] 52% 1.1s167.3 MiB [] 53% 1.1s167.3 MiB [] 54% 1.0s167.3 MiB [] 55% 1.0s167.3 MiB [] 56% 1.0s167.3 MiB [] 57% 1.0s167.3 MiB [] 58% 0.9s167.3 MiB [] 59% 0.9s167.3 MiB [] 60% 0.9s167.3 MiB [] 61% 0.8s167.3 MiB [] 62% 0.8s167.3 MiB [] 63% 0.8s167.3 MiB [] 64% 0.8s167.3 MiB [] 65% 0.7s167.3 MiB [] 66% 0.7s167.3 MiB [] 67% 0.7s167.3 MiB [] 68% 0.7s167.3 MiB [] 69% 0.7s167.3 MiB [] 70% 0.7s167.3 MiB [] 71% 0.6s167.3 MiB [] 72% 0.6s167.3 MiB [] 73% 0.6s167.3 MiB [] 74% 0.6s167.3 MiB [] 75% 0.6s167.3 MiB [] 75% 0.5s167.3 MiB [] 76% 0.5s167.3 MiB [] 77% 0.5s167.3 MiB [] 78% 0.5s167.3 MiB [] 79% 0.5s167.3 MiB [] 80% 0.4s167.3 MiB [] 81% 0.4s167.3 MiB [] 82% 0.4s167.3 MiB [] 83% 0.4s167.3 MiB [] 84% 0.4s167.3 MiB [] 85% 0.3s167.3 MiB [] 86% 0.3s167.3 MiB [] 87% 0.3s167.3 MiB [] 88% 0.3s167.3 MiB [] 89% 0.2s167.3 MiB [] 90% 0.2s167.3 MiB [] 91% 0.2s167.3 MiB [] 92% 0.2s167.3 MiB [] 93% 0.2s167.3 MiB [] 94% 0.1s167.3 MiB [] 95% 0.1s167.3 MiB [] 96% 0.1s167.3 MiB [] 97% 0.0s167.3 MiB [] 98% 0.0s167.3 MiB [] 99% 0.0s167.3 MiB [] 100% 0.0s
Chrome for Testing 145.0.7632.6 (playwright chromium v1208) downloaded to /root/.cache/ms-playwright/chromium-1208
Downloading FFmpeg (playwright ffmpeg v1011) from https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-linux.zip
(node:1445) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
2.3 MiB [] 0% 0.0s2.3 MiB [] 6% 0.3s2.3 MiB [] 19% 0.1s2.3 MiB [] 48% 0.1s2.3 MiB [] 99% 0.0s2.3 MiB [] 100% 0.0s
FFmpeg (playwright ffmpeg v1011) downloaded to /root/.cache/ms-playwright/ffmpeg-1011
Downloading Chrome Headless Shell 145.0.7632.6 (playwright chromium-headless-shell v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/linux64/chrome-headless-shell-linux64.zip
(node:1460) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
110.9 MiB [] 0% 0.0s110.9 MiB [] 0% 37.7s110.9 MiB [] 0% 16.5s110.9 MiB [] 0% 14.5s110.9 MiB [] 0% 11.1s110.9 MiB [] 0% 10.1s110.9 MiB [] 1% 7.8s110.9 MiB [] 2% 6.1s110.9 MiB [] 2% 5.0s110.9 MiB [] 3% 4.0s110.9 MiB [] 5% 3.3s110.9 MiB [] 5% 3.0s110.9 MiB [] 6% 3.0s110.9 MiB [] 8% 2.5s110.9 MiB [] 9% 2.2s110.9 MiB [] 11% 2.0s110.9 MiB [] 12% 1.9s110.9 MiB [] 14% 1.8s110.9 MiB [] 14% 1.7s110.9 MiB [] 16% 1.6s110.9 MiB [] 18% 1.5s110.9 MiB [] 19% 1.5s110.9 MiB [] 20% 1.4s110.9 MiB [] 22% 1.3s110.9 MiB [] 23% 1.3s110.9 MiB [] 24% 1.3s110.9 MiB [] 26% 1.2s110.9 MiB [] 28% 1.2s110.9 MiB [] 29% 1.1s110.9 MiB [] 31% 1.1s110.9 MiB [] 32% 1.1s110.9 MiB [] 33% 1.0s110.9 MiB [] 35% 1.0s110.9 MiB [] 37% 0.9s110.9 MiB [] 39% 0.9s110.9 MiB [] 41% 0.8s110.9 MiB [] 43% 0.8s110.9 MiB [] 44% 0.8s110.9 MiB [] 46% 0.7s110.9 MiB [] 48% 0.7s110.9 MiB [] 50% 0.7s110.9 MiB [] 52% 0.6s110.9 MiB [] 54% 0.6s110.9 MiB [] 56% 0.5s110.9 MiB [] 58% 0.5s110.9 MiB [] 60% 0.5s110.9 MiB [] 61% 0.5s110.9 MiB [] 63% 0.4s110.9 MiB [] 65% 0.4s110.9 MiB [] 66% 0.4s110.9 MiB [] 67% 0.4s110.9 MiB [] 68% 0.4s110.9 MiB [] 69% 0.4s110.9 MiB [] 70% 0.4s110.9 MiB [] 72% 0.3s110.9 MiB [] 73% 0.3s110.9 MiB [] 74% 0.3s110.9 MiB [] 75% 0.3s110.9 MiB [] 76% 0.3s110.9 MiB [] 78% 0.3s110.9 MiB [] 79% 0.3s110.9 MiB [] 80% 0.2s110.9 MiB [] 82% 0.2s110.9 MiB [] 84% 0.2s110.9 MiB [] 85% 0.2s110.9 MiB [] 86% 0.2s110.9 MiB [] 88% 0.2s110.9 MiB [] 89% 0.1s110.9 MiB [] 91% 0.1s110.9 MiB [] 93% 0.1s110.9 MiB [] 95% 0.1s110.9 MiB [] 96% 0.0s110.9 MiB [] 98% 0.0s110.9 MiB [] 99% 0.0s110.9 MiB [] 100% 0.0s
Chrome Headless Shell 145.0.7632.6 (playwright chromium-headless-shell v1208) downloaded to /root/.cache/ms-playwright/chromium_headless_shell-1208

In [ ]:
# System deps (force install + verify)
!apt-get -qq update
!apt-get -qq install -y libatk1.0-0 libatk-bridge2.0-0

# Verify the library file exists
!ldconfig -p | grep -E "libatk-1.0.so.0|libatk-bridge" || true
!ls -l /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 || true

# Reinstall playwright + browser (fresh)
!pip -q install -U playwright
!playwright install chromium

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
	libatk-1.0.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libatk-1.0.so.0
	libatk-bridge-2.0.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libatk-bridge-2.0.so.0
lrwxrwxrwx 1 root root 23 Mar 23  2022 /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0 -> libatk-1.0.so.0.23609.1

In [ ]:
!pip -q install playwright

# System deps needed by Chromium in Colab
!apt-get -qq update
!apt-get -qq install -y \
  libatk-1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libgbm1 \
  libnspr4 libnss3 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 \
  libxkbcommon0 libasound2 libpangocairo-1.0-0 libpango-1.0-0 \
  libgtk-3-0

# Install browser binaries
!playwright install chromium

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
E: Unable to locate package libatk-1.0-0
E: Couldn't find any package by glob 'libatk-1.0-0'
E: Couldn't find any package by regex 'libatk-1.0-0'

In [ ]:
!pip -q install playwright
!playwright install chromium

In [ ]:
import asyncio
import pandas as pd
import re
import time
from playwright.async_api import async_playwright

MOVIES = [
    ('tt12735488', 'Kalki 2898 AD',     'https://www.imdb.com/title/tt12735488/reviews/'),
    ('tt23804696', 'HIT: The 3rd Case', 'https://www.imdb.com/title/tt23804696/reviews/'),
    ('tt21190272', 'Pushpa 2',          'https://www.imdb.com/title/tt21190272/reviews/'),
    ('tt13186482', 'Animal',            'https://www.imdb.com/title/tt13186482/reviews/'),
    ('tt14539740', 'Leo',               'https://www.imdb.com/title/tt14539740/reviews/'),
]

async def scrape_movie(playwright, movie_id, movie_title, url, target=500):
    print(f'\n>>> Scraping: {movie_title} (target={target})')

    browser = await playwright.chromium.launch(headless=True)
    context = await browser.new_context(
        user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                   'AppleWebKit/537.36 (KHTML, like Gecko) '
                   'Chrome/120.0.0.0 Safari/537.36',
        viewport={'width': 1920, 'height': 1080}
    )
    page = await context.new_page()

    collected = []
    seen = set()

    try:
        await page.goto(url, timeout=30000, wait_until='domcontentloaded')
        await page.wait_for_selector('article', timeout=15000)
        await asyncio.sleep(2)

        rounds_no_change = 0
        prev_count = -1

        while len(collected) < target:
            # Count current reviews
            articles = await page.query_selector_all('article[data-testid="review"], article')
            count = len(articles)
            print(f'  Loaded {count} reviews...', end='\r')

            if count == prev_count:
                rounds_no_change += 1
            else:
                rounds_no_change = 0
            if rounds_no_change >= 5:
                print(f'\n  No new reviews loading, stopping.')
                break
            prev_count = count

            # Try clicking any load-more button
            btn = await page.query_selector('button.ipc-see-more__button')
            if btn:
                try:
                    await btn.scroll_into_view_if_needed()
                    await asyncio.sleep(0.5)
                    await btn.click()
                    await asyncio.sleep(2)
                except Exception:
                    pass
            else:
                # Scroll to trigger lazy loading
                await page.evaluate('window.scrollTo(0, document.body.scrollHeight)')
                await asyncio.sleep(2)

            if count >= target:
                break

        # Parse all loaded reviews
        print(f'\n  Parsing reviews...')
        articles = await page.query_selector_all('article[data-testid="review"], article')
        print(f'  Found {len(articles)} review elements')

        for art in articles:
            try:
                async def safe_text(selector):
                    try:
                        el = await art.query_selector(selector)
                        return (await el.inner_text()).strip() if el else 'N/A'
                    except:
                        return 'N/A'

                rating   = await safe_text('span[data-testid="rating"] span.ipc-rating-star--rating')
                if rating == 'N/A':
                    rating = await safe_text('.ipc-rating-star--rating')

                rev_title = await safe_text('span[data-testid="review-summary"]')
                if rev_title == 'N/A':
                    rev_title = await safe_text('h3')

                author = await safe_text('a[data-testid="author-link"]')
                if author == 'N/A':
                    author = await safe_text('a[href*="/user/"]')

                date   = await safe_text('li[data-testid="review-date"]')
                review = await safe_text('div[data-testid="review-overflow"]')
                if review == 'N/A':
                    review = await safe_text('div[class*="content"]')

                review = re.sub(r'^\d+\n/10\n', '', review).strip()

                key = (author, date, review[:80])
                if key not in seen and len(review) > 20:
                    seen.add(key)
                    collected.append({
                        'movie_id':    movie_id,
                        'movie_title': movie_title,
                        'rating':      rating,
                        'rev_title':   rev_title,
                        'author':      author,
                        'date':        date,
                        'review':      review,
                    })

                if len(collected) >= target:
                    break

            except Exception:
                continue

    except Exception as e:
        print(f'  Error: {e}')
    finally:
        await browser.close()

    print(f'  ✅ Got {len(collected)} reviews for {movie_title}')
    return collected


async def main():
    all_reviews = []

    async with async_playwright() as playwright:
        for movie_id, movie_title, url in MOVIES:
            if len(all_reviews) >= 1000:
                break
            remaining = 1000 - len(all_reviews)
            batch = await scrape_movie(playwright, movie_id, movie_title, url, target=remaining)
            all_reviews.extend(batch)
            print(f'Running total: {len(all_reviews)} / 1000')
            await asyncio.sleep(3)

    df = pd.DataFrame(all_reviews)
    print(f'\n✅ Total reviews collected: {len(df)}')
    if len(df) > 0:
        print(df['movie_title'].value_counts())
        display(df.head(3))
        df.to_csv('imdb_reviews_raw.csv', index=False)
        print('Saved: imdb_reviews_raw.csv')
    else:
        print('No reviews collected.')

    return df

df =!pip -q install nest_asyncio

import nest_asyncio
import asyncio

nest_asyncio.apply()
df = asyncio.get_event_loop().run_until_complete(main())
df.head()

WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.

>>> Scraping: Kalki 2898 AD (target=1000)

WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.

WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.

WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.

WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.

WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.

WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.
WARNING:asyncio:pipe closed by peer or os.write(pipe, data) raised exception.

  Loaded 967 reviews...
  No new reviews loading, stopping.

  Parsing reviews...
  Found 967 review elements
  ✅ Got 922 reviews for Kalki 2898 AD
Running total: 922 / 1000

>>> Scraping: HIT: The 3rd Case (target=78)

  Parsing reviews...
  Found 125 review elements
  ✅ Got 78 reviews for HIT: The 3rd Case
Running total: 1000 / 1000

✅ Total reviews collected: 1000
movie_title
Kalki 2898 AD        922
HIT: The 3rd Case     78
Name: count, dtype: int64

,movie_id,movie_title,rating,rev_title,author,date,review
0,tt12735488,Kalki 2898 AD,6,"Atrocious first half, forced comedy and terrib...",rishavk-44894,N/A,The soaring epicness of second part of the fil...
1,tt12735488,Kalki 2898 AD,8,"Good attempt, story and is engaging, but",adipawar-98409,N/A,"Good attempt, story and is engaging, but\nSpoiler"
2,tt12735488,Kalki 2898 AD,6,Could have been so so much better,uselessmail-18000,N/A,I don't understand the obsession with hero ent...

Saved: imdb_reviews_raw.csv

,movie_id,movie_title,rating,rev_title,author,date,review
0,tt12735488,Kalki 2898 AD,6,"Atrocious first half, forced comedy and terrib...",rishavk-44894,N/A,The soaring epicness of second part of the fil...
1,tt12735488,Kalki 2898 AD,8,"Good attempt, story and is engaging, but",adipawar-98409,N/A,"Good attempt, story and is engaging, but\nSpoiler"
2,tt12735488,Kalki 2898 AD,6,Could have been so so much better,uselessmail-18000,N/A,I don't understand the obsession with hero ent...
3,tt12735488,Kalki 2898 AD,N/A,Kalki: Borrowed Ideas and Awkward Execution Ma...,reed-54805,N/A,I just watched Kalki and it's hard to express ...
4,tt12735488,Kalki 2898 AD,8,A visual treat with a strong story & characters,maheshgade,N/A,"A unique genre, a well written story (script) ..."

# Question 2 (15 points)

Write a python program to **clean the text data** you collected in the previous question and save the clean data in a new column in the csv file. The data cleaning steps include: [Code and output is required for each part]

(1) Remove noise, such as special characters and punctuations.

(2) Remove numbers.

(3) Remove stopwords by using the stopwords list.

(4) Lowercase all texts

(5) Stemming.

(6) Lemmatization.

In [ ]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize

# download required nltk data
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

df = pd.read_csv('imdb_reviews_raw.csv')
df.dropna(subset=['review'], inplace=True)
df.reset_index(drop=True, inplace=True)

stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()


# --- Step 1: Remove special characters and punctuation ---
def remove_noise(text):
    # strip HTML tags if any slipped through
    text = re.sub(r'<[^>]+>', ' ', text)
    # remove anything that's not a letter or a space
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    # collapse multiple spaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['clean_step1'] = df['review'].apply(remove_noise)
print('Step 1 - Noise removed (sample):')
print(df['clean_step1'].head(3))


# --- Step 2: Remove numbers ---
def remove_numbers(text):
    return re.sub(r'\d+', '', text).strip()

df['clean_step2'] = df['clean_step1'].apply(remove_numbers)
print('\nStep 2 - Numbers removed (sample):')
print(df['clean_step2'].head(3))


# --- Step 3: Remove stopwords ---
def remove_stopwords(text):
    tokens = word_tokenize(text)
    filtered = [w for w in tokens if w.lower() not in stop_words and len(w) > 1]
    return ' '.join(filtered)

df['clean_step3'] = df['clean_step2'].apply(remove_stopwords)
print('\nStep 3 - Stopwords removed (sample):')
print(df['clean_step3'].head(3))


# --- Step 4: Lowercase all text ---
df['clean_step4'] = df['clean_step3'].apply(lambda x: x.lower())
print('\nStep 4 - Lowercased (sample):')
print(df['clean_step4'].head(3))


# --- Step 5: Stemming ---
def apply_stemming(text):
    tokens = word_tokenize(text)
    stemmed = [stemmer.stem(w) for w in tokens]
    return ' '.join(stemmed)

df['clean_stemmed'] = df['clean_step4'].apply(apply_stemming)
print('\nStep 5 - Stemmed (sample):')
print(df['clean_stemmed'].head(3))


# --- Step 6: Lemmatization ---
def apply_lemmatization(text):
    tokens = word_tokenize(text)
    lemmatized = [lemmatizer.lemmatize(w) for w in tokens]
    return ' '.join(lemmatized)

df['clean_lemmatized'] = df['clean_step4'].apply(apply_lemmatization)
print('\nStep 6 - Lemmatized (sample):')
print(df['clean_lemmatized'].head(3))


df['clean_text'] = df['clean_lemmatized']

df.to_csv('imdb_reviews_cleaned.csv', index=False)
print('\nCleaned data saved to imdb_reviews_cleaned.csv')
print(f'Total rows: {len(df)}')
print(df[['review', 'clean_text']].head())

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

Step 1 - Noise removed (sample):
0    The soaring epicness of second part of the fil...
1       Good attempt story and is engaging but Spoiler
2    I don t understand the obsession with hero ent...
Name: clean_step1, dtype: object

Step 2 - Numbers removed (sample):
0    The soaring epicness of second part of the fil...
1       Good attempt story and is engaging but Spoiler
2    I don t understand the obsession with hero ent...
Name: clean_step2, dtype: object

Step 3 - Stopwords removed (sample):
0    soaring epicness second part film excellent cl...
1                  Good attempt story engaging Spoiler
2    understand obsession hero entry people good st...
Name: clean_step3, dtype: object

Step 4 - Lowercased (sample):
0    soaring epicness second part film excellent cl...
1                  good attempt story engaging spoiler
2    understand obsession hero entry people good st...
Name: clean_step4, dtype: object

Step 5 - Stemmed (sample):
0    soar epic second part film excel climax taint ...
1                     good attempt stori engag spoiler
2    understand obsess hero entri peopl good stori ...
Name: clean_stemmed, dtype: object

Step 6 - Lemmatized (sample):
0    soaring epicness second part film excellent cl...
1                  good attempt story engaging spoiler
2    understand obsession hero entry people good st...
Name: clean_lemmatized, dtype: object

Cleaned data saved to imdb_reviews_cleaned.csv
Total rows: 1000
                                              review  \
0  The soaring epicness of second part of the fil...
1  Good attempt, story and is engaging, but\nSpoiler
2  I don't understand the obsession with hero ent...
3  I just watched Kalki and it's hard to express ...
4  A unique genre, a well written story (script) ...

                                          clean_text
0  soaring epicness second part film excellent cl...
1                good attempt story engaging spoiler
2  understand obsession hero entry people good st...
3  watched kalki hard express disappointment firs...
4  unique genre well written story script strong ...

# Question 3 (15 points)

Write a python program to **conduct syntax and structure analysis of the clean text** you just saved above. The syntax and structure analysis includes:

(1) **Parts of Speech (POS) Tagging:** Tag Parts of Speech of each word in the text, and calculate the total number of N(oun), V(erb), Adj(ective), Adv(erb), respectively.

(2) **Constituency Parsing and Dependency Parsing:** print out the constituency parsing trees and dependency parsing trees of all the sentences. Using one sentence as an example to explain your understanding about the constituency parsing tree and dependency parsing tree.

(3) **Named Entity Recognition:** Extract all the entities such as person names, organizations, locations, product names, and date from the clean texts, calculate the count of each entity.

In [ ]:
import pandas as pd
import nltk
from nltk import pos_tag, word_tokenize, ne_chunk
from nltk.tree import Tree
from collections import Counter
import spacy

nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('averaged_perceptron_tagger_eng')

df = pd.read_csv('imdb_reviews_cleaned.csv')
df.dropna(subset=['clean_text'], inplace=True)

# using a smaller subset for heavy tasks to keep runtime manageable
sample_df = df.head(200).copy()


# ================================================================
# Part 1: POS Tagging - count Nouns, Verbs, Adjectives, Adverbs
# ================================================================

noun_count = 0
verb_count = 0
adj_count  = 0
adv_count  = 0

for text in sample_df['clean_text']:
    tokens = word_tokenize(str(text))
    tags = pos_tag(tokens)
    for word, tag in tags:
        if tag.startswith('NN'):   noun_count += 1
        elif tag.startswith('VB'): verb_count += 1
        elif tag.startswith('JJ'): adj_count  += 1
        elif tag.startswith('RB'): adv_count  += 1

print('=== POS Tag Counts (across 200 reviews) ===')
print(f'Nouns (NN):      {noun_count}')
print(f'Verbs (VB):      {verb_count}')
print(f'Adjectives (JJ): {adj_count}')
print(f'Adverbs (RB):    {adv_count}')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

=== POS Tag Counts (across 200 reviews) ===
Nouns (NN):      8758
Verbs (VB):      3259
Adjectives (JJ): 4293
Adverbs (RB):    1416

In [ ]:
# ================================================================
# Part 2: Constituency Parsing and Dependency Parsing
# ================================================================

# --- Constituency Parsing using NLTK CFG grammar ---
from nltk import CFG, ChartParser
from nltk.tokenize import sent_tokenize

try:
    nlp = spacy.load('en_core_web_sm')
except OSError:
    import subprocess
    subprocess.run(['python', '-m', 'spacy', 'download', 'en_core_web_sm'])
    nlp = spacy.load('en_core_web_sm')

print('=== Dependency Parse Trees (first 5 reviews, first sentence each) ===')
for i, text in enumerate(sample_df['clean_text'].head(5)):
    sentences = sent_tokenize(str(text))
    if sentences:
        sent = sentences[0]
        doc = nlp(sent)
        print(f'\nReview {i+1} - Sentence: "{sent[:80]}..."')
        print(f'{"Token":<15} {"Dep":<12} {"Head":<15} {"POS":<8}')
        print('-' * 55)
        for token in doc:
            print(f'{token.text:<15} {token.dep_:<12} {token.head.text:<15} {token.pos_:<8}')

=== Dependency Parse Trees (first 5 reviews, first sentence each) ===

Review 1 - Sentence: "soaring epicness second part film excellent climax tainted bloated boring techni..."
Token           Dep          Head            POS
-------------------------------------------------------
soaring         amod         climax          VERB
epicness        amod         climax          ADJ
second          amod         part            ADJ
part            compound     climax          NOUN
film            nmod         climax          NOUN
excellent       amod         climax          ADJ
climax          nsubj        tainted         NOUN
tainted         ROOT         tainted         VERB
bloated         amod         half            ADJ
boring          amod         half            ADJ
technically     advmod       terrible        ADV
terrible        amod         half            ADJ
first           amod         half            ADJ
half            nmod         dialogue        NOUN
cringe          compound     dialogue        NOUN
dialogue        nmod         scene           NOUN
poorly          advmod       choreographed   ADV
choreographed   amod         scene           ADJ
action          compound     scene           NOUN
scene           nmod         subplots        NOUN
unnecessary     amod         subplots        ADJ
subplots        compound     prop            NOUN
prop            nsubj        looked          NOUN
used            acl          prop            VERB
throughout      prep         used            ADP
movie           pobj         throughout      NOUN
looked          ccomp        tainted         VERB
like            prep         looked          ADP
cheap           amod         inspiration     ADJ
foam            npadvmod     much            NOUN
much            amod         inspiration     ADJ
inspiration     pobj         like            NOUN
drawn           acl          inspiration     VERB
hollywood       compound     movie           NOUN
movie           dobj         drawn           NOUN
first           amod         attempt         ADJ
attempt         advcl        looked          NOUN
nag             intj         attempt         INTJ
ashwin          compound     average         PROPN
average         amod         hope            ADJ
best            amod         hope            ADJ
hope            nsubj        improves        NOUN
improves        acl          attempt         VERB
significantly   advmod       second          ADV
second          amod         mahabharata     ADJ
part            compound     mahabharata     NOUN
film            compound     mahabharata     NOUN
focus           compound     mahabharata     NOUN
mahabharata     nsubj        adapt           NOUN
adapt           ccomp        improves        VERB
faithfully      advmod       possible        ADV
possible        amod         disappointing   ADJ
sci             compound     fi              PROPN
fi              compound     disappointing   NOUN
element         compound     movie           NOUN
movie           compound     disappointing   NOUN
disappointing   dobj         adapt           NOUN
whereas         prep         tainted         SCONJ
character       pobj         whereas         NOUN
great           amod         epic            ADJ
epic            advcl        tainted         ADJ
thoroughly      advmod       exhilarating    ADV
exhilarating    advcl        tainted         VERB

Review 2 - Sentence: "good attempt story engaging spoiler..."
Token           Dep          Head            POS
-------------------------------------------------------
good            amod         story           ADJ
attempt         compound     story           NOUN
story           nmod         spoiler         NOUN
engaging        amod         spoiler         VERB
spoiler         ROOT         spoiler         NOUN

Review 3 - Sentence: "understand obsession hero entry people good story stick need star bigger story f..."
Token           Dep          Head            POS
-------------------------------------------------------
understand      ROOT         understand      VERB
obsession       compound     hero            NOUN
hero            compound     entry           NOUN
entry           compound     people          NOUN
people          nmod         stick           NOUN
good            amod         story           ADJ
story           compound     stick           NOUN
stick           nsubj        need            NOUN
need            compound     star            VERB
star            nmod         story           NOUN
bigger          amod         story           ADJ
story           nmod         story           NOUN
first           amod         hour            ADJ
hour            compound     story           NOUN
story           nsubj        skippable       NOUN
skippable       ccomp        understand      ADJ
completely      advmod       rest            ADV
rest            amod         vfx             ADJ
vfx             compound     notch           NOUN
top             amod         notch           ADJ
notch           dobj         skippable       NOUN
even            advmod       ending          ADV
ending          advcl        skippable       VERB
good            amod         obsession       ADJ
obsession       compound     hero            NOUN
hero            dobj         ending          NOUN
need            aux          director        AUX
stop            aux          director        AUX
also            advmod       director        ADV
director        conj         understand      VERB
invent          compound     character       ADJ
character       compound     reference       NOUN
kalki           compound     reference       NOUN
reference       nsubj        took            NOUN
took            conj         understand      VERB
mahabharata     dobj         took            NOUN
please          intj         took            INTJ
respectful      amod         part            ADJ
part            compound     history         NOUN
history         compound     something       NOUN
something       nsubj        make            PRON
mock            amod         something       ADJ
make            conj         took            VERB
serious         amod         want            ADJ
want            ccomp        make            VERB
hero            compound     entry           NOUN
entry           nsubj        want            NOUN
want            ccomp        want            VERB
film            npadvmod     useless         NOUN
useless         amod         comedy          ADJ
unfunny         amod         comedy          ADJ
comedy          dobj         want            NOUN

Review 4 - Sentence: "watched kalki hard express disappointment first movie riddled unnecessary comedi..."
Token           Dep          Head            POS
-------------------------------------------------------
watched         advcl        feel            VERB
kalki           dobj         watched         PROPN
hard            advmod       express         ADV
express         amod         dialogue        ADJ
disappointment  nmod         movie           NOUN
first           amod         movie           ADJ
movie           npadvmod     riddled         NOUN
riddled         amod         dialogue        VERB
unnecessary     amod         dialogue        ADJ
comedic         amod         dialogue        ADJ
dialogue        nsubj        feel            NOUN
feel            ROOT         feel            VERB
completely      advmod       place           ADV
place           acomp        feel            NOUN
especially      advmod       given           ADV
given           advcl        feel            VERB
supposedly      advmod       intense         ADV
intense         amod         prabhas         ADJ
theme           compound     prabhas         NOUN
prabhas         nsubj        powerhouse      NOUN
usually         advmod       powerhouse      ADV
powerhouse      conj         feel            VERB
sadly           advmod       come            ADV
come            dep          feel            VERB
across          prep         come            ADP
clownish        amod         performance     ADJ
character       compound     performance     NOUN
performance     pobj         across          NOUN
awkward         advmod       come            ADV
forced          conj         feel            VERB
making          xcomp        forced          VERB
difficult       acomp        making          ADJ
take            xcomp        forced          VERB
film            dobj         take            NOUN
seriously       advmod       kyra            ADV
kyra            compound     character       PROPN
character       nsubj        add             NOUN
add             ccomp        forced          VERB
little          amod         screen          ADJ
value           compound     screen          NOUN
screen          compound     time            NOUN
time            npadvmod     dedicated       NOUN
dedicated       amod         movie           VERB
pointless       amod         movie           ADJ
talk            nmod         drag            NOUN
drag            nmod         movie           NOUN
narrative       amod         movie           NOUN
entire          amod         movie           ADJ
movie           nsubj        feel            NOUN
feel            conj         feel            VERB
like            prep         feel            ADP
overdoing       pcomp        like            VERB
everything      compound     action          PRON
action          compound     sequence        NOUN
sequence        nmod         comedy          NOUN
emotional       amod         moment          ADJ
moment          npadvmod     supposed        NOUN
supposed        amod         comedy          VERB
comedy          compound     kamal           NOUN
jarringly       advmod       kamal           ADV
sync            compound     movie           NOUN
rest            compound     movie           NOUN
movie           compound     kamal           NOUN
kamal           nsubj        haasan          NOUN
haasan          ccomp        overdoing       ADJ
despite         prep         overdoing       SCONJ
legendary       amod         actor           ADJ
actor           compound     presence        NOUN
almost          advmod       screen          ADV
role            compound     screen          NOUN
screen          compound     presence        NOUN
presence        pobj         despite         NOUN
feel            conj         feel            VERB
like            mark         draw            SCONJ
used            amod         name            VERB
name            nsubj        draw            NOUN
draw            xcomp        feel            VERB
audience        nmod         screen          NOUN
real            amod         contribution    ADJ
contribution    compound     screen          NOUN
screen          dobj         draw            NOUN
additionally    advmod       set             ADV
set             acl          screen          VERB
blatantly       advmod       borrows         ADV
borrows         dep          feel            VERB
mad             amod         road            ADJ
max             compound     fury            PROPN
fury            compound     road            NOUN
road            nsubj        fails           NOUN
fails           ccomp        borrows         VERB
miserably       advmod       fails           ADV
capture         dep          fails           VERB
essence         dobj         capture         NOUN
original        amod         end             ADJ
end             compound     kalki           NOUN
kalki           nsubj        executed        PROPN
poorly          advmod       executed        ADV
executed        conj         fails           VERB
overhyped       amod         mess            ADJ
mess            dobj         executed        NOUN
one             nummod       pas             NUM
hard            amod         pas             ADJ
pas             dobj         executed        NOUN

Review 5 - Sentence: "unique genre well written story script strong character give movie strong start ..."
Token           Dep          Head            POS
-------------------------------------------------------
unique          amod         character       ADJ
genre           nmod         script          NOUN
well            advmod       written         ADV
written         amod         script          VERB
story           compound     script          NOUN
script          nmod         character       NOUN
strong          amod         character       ADJ
character       nsubj        give            NOUN
give            ROOT         give            VERB
movie           dative       give            NOUN
strong          amod         start           ADJ
start           nmod         visuals         VERB
extravagant     amod         visuals         ADJ
visuals         dobj         give            NOUN
detailed        acl          visuals         VERB
crisp           amod         vfx             ADJ
vfx             dobj         detailed        NOUN
give            dative       give            VERB
audience        dative       give            NOUN
much            advmod       needed          ADV
needed          amod         thrill          VERB
thrill          dobj         give            NOUN
however         advmod       movie           ADV
one             nummod       forgo           NUM
forgo           compound     vfx             NOUN
resemblance     compound     vfx             NOUN
vfx             compound     shot            NOUN
shot            compound     movie           NOUN
movie           dobj         give            NOUN
like            prep         movie           ADP
dune            compound     war             PROPN
star            compound     war             PROPN
war             nmod         transformer     PROPN
mad             amod         transformer     PROPN
max             nmod         transformer     PROPN
black           amod         transformer     ADJ
panther         compound     transformer     NOUN
transformer     pobj         like            NOUN
although        mark         producing       SCONJ
huge            amod         team            ADJ
kudos           compound     team            NOUN
team            nsubj        producing       NOUN
producing       advcl        give            VERB
movie           npadvmod     equivalent      NOUN
equivalent      amod         scale           ADJ
scale           npadvmod     mentioned       NOUN
mentioned       amod         time            VERB
movie           nmod         time            NOUN
pro             amod         time            ADJ
time            dobj         producing       NOUN
taken           advcl        give            VERB
build           compound     character       NOUN
character       nsubj        explain         NOUN
explain         conj         give            VERB
world           nsubj        stunt           NOUN
stunt           ccomp        explain         VERB
crisp           amod         visuals         ADJ
bright          amod         visuals         ADJ
visuals         nsubj        screenplay      NOUN
screenplay      conj         give            VERB
direction       compound     comedy          NOUN
comedy          compound     score           NOUN
con             compound     background      NOUN
music           compound     background      NOUN
background      compound     score           NOUN
score           nsubj        unique          NOUN
unique          ccomp        screenplay      ADJ
give            dative       give            VERB
much            advmod       needed          ADV
needed          amod         visuals         VERB
grandeur        compound     visuals         ADJ
visuals         compound     scene           NOUN
scene           nmod         use             NOUN
repeated        amod         use             VERB
use             dobj         give            NOUN
score           dobj         use             NOUN
abruptly        advmod       high            ADV
high            amod         stunt           ADJ
background      compound     stunt           NOUN
score           compound     stunt           NOUN
stunt           dobj         use             NOUN
editing         advcl        give            VERB
especially      advmod       first           ADV
first           advmod       editing         ADJ
half            npadvmod     give            NOUN

In [ ]:
# --- Constituency Parsing using benepar (Berkeley Neural Parser) ---
# If benepar is not installed, we show NLTK-based shallow parsing instead

try:
    import benepar
    benepar.download('benepar_en3')
    nlp_cp = spacy.load('en_core_web_sm')
    nlp_cp.add_pipe('benepar', config={'model': 'benepar_en3'})
    use_benepar = True
except Exception:
    use_benepar = False
    print('benepar not available, using NLTK shallow chunking for constituency demo.')

example_sentence = str(sample_df['clean_text'].iloc[0]).split('.')[0]
print(f'Example sentence: "{example_sentence}"\n')

if use_benepar:
    doc_cp = nlp_cp(example_sentence)
    for sent in doc_cp.sents:
        print('Constituency Parse Tree:')
        print(sent._.parse_string)
else:
    grammar = r"""
      NP: {<DT|PP\$>?<JJ>*<NN>}
      VP: {<VBD|VBZ|VBP><RB>?<VB>?}
    """
    cp = nltk.RegexpParser(grammar)
    tokens = word_tokenize(example_sentence)
    tagged = pos_tag(tokens)
    tree = cp.parse(tagged)
    print('Shallow Constituency Parse (NP/VP chunks):')
    print(tree)
    tree.pretty_print()

print("""
Explanation:
- Constituency Parsing breaks a sentence into nested phrases (NP, VP, PP, etc.).
  Each node in the tree is a phrase type, and the leaves are individual words.
  For example: 'The movie was great' -> (S (NP The movie) (VP was (ADJP great)))
  This shows 'The movie' is a Noun Phrase and 'was great' is a Verb Phrase.

- Dependency Parsing shows grammatical relationships between words.
  Every word points to its 'head' (the word it depends on), with a labeled relation.
  For example: 'great' -> nsubj of 'was', and 'movie' -> det modified by 'The'.
  Unlike constituency parsing, there are no phrase nodes -- just word-to-word links.
""")

benepar not available, using NLTK shallow chunking for constituency demo.
Example sentence: "soaring epicness second part film excellent climax tainted bloated boring technically terrible first half cringe dialogue poorly choreographed action scene unnecessary subplots prop used throughout movie looked like cheap foam much inspiration drawn hollywood movie first attempt nag ashwin average best hope improves significantly second part film focus mahabharata adapt faithfully possible sci fi element movie disappointing whereas character great epic thoroughly exhilarating"

Shallow Constituency Parse (NP/VP chunks):
(S
  soaring/VBG
  (NP epicness/JJ second/JJ part/NN)
  (NP film/NN)
  (NP excellent/JJ climax/NN)
  (VP tainted/VBD)
  (NP bloated/JJ boring/NN)
  technically/RB
  (NP terrible/JJ first/JJ half/NN)
  (NP cringe/NN)
  (NP dialogue/NN)
  poorly/RB
  choreographed/VBN
  (NP action/NN)
  (NP scene/NN)
  unnecessary/JJ
  subplots/NNS
  (NP prop/NN)
  used/VBN
  throughout/IN
  (NP movie/NN)
  looked/VBN
  like/IN
  (NP cheap/JJ foam/NN)
  (NP much/JJ inspiration/NN)
  (NP drawn/NN)
  (NP hollywood/NN)
  (NP movie/NN)
  (NP first/JJ attempt/NN)
  (NP nag/NN)
  ashwin/JJ
  average/JJ
  best/JJS
  (NP hope/NN)
  (VP improves/VBZ significantly/RB)
  (NP second/JJ part/NN)
  (NP film/NN)
  (NP focus/NN)
  (NP mahabharata/NN)
  (NP adapt/NN)
  faithfully/RB
  (NP possible/JJ sci/NN)
  (NP fi/JJ element/JJ movie/NN)
  (NP disappointing/JJ whereas/JJ character/NN)
  great/JJ
  epic/JJ
  thoroughly/RB
  exhilarating/VBG)
                                                                                                                                                                                                                                                                                                                                                                        S
      __________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________|_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
     |            |            |           |              |             |          |           |           |         |        |         |         |           |          |        |          |              |                         NP               NP                 NP                VP                 NP                          NP                NP         NP         NP       NP       NP      NP              NP                  NP                   NP         NP         NP              NP              NP      NP                 VP                             NP            NP      NP          NP          NP                 NP                  NP                                   NP
     |            |            |           |              |             |          |           |           |         |        |         |         |           |          |        |          |              |               __________|________        |          ________|______           |           _______|______            _________|________         |          |          |        |        |       |         ______|_____         _____|________            |          |          |         ______|______         |       |          ________|_________               ______|_____        |       |           |           |           _______|____        _______|_________              _____________|___________
soaring/VBG technically/RB poorly/RB choreographed/ unnecessary/JJ subplots/NNS used/VBN throughout/IN looked/VBN like/IN ashwin/JJ average/JJ best/JJS faithfully/RB great/JJ epic/JJ thoroughly/RB exhilarating/VBG epicness/JJ second/JJ part/NN film/NN excellent/JJ     climax/NN tainted/VBD bloated/JJ     boring/NN terrible/JJ first/JJ half/NN cringe/NN dialogue/NN action/NN scene/NN prop/NN movie/NN cheap/JJ     foam/NN much/JJ     inspiration/NN drawn/NN hollywood/NN movie/NN first/JJ     attempt/NN nag/NN hope/NN improves/VBZ     significantly/RB second/JJ     part/NN film/NN focus/NN mahabharata/NN adapt/NN possible/JJ     sci/NN fi/JJ element/JJ movie/NN disappointing/JJ whereas/JJ character/NN
                                          VBN


Explanation:
- Constituency Parsing breaks a sentence into nested phrases (NP, VP, PP, etc.).
  Each node in the tree is a phrase type, and the leaves are individual words.
  For example: 'The movie was great' -> (S (NP The movie) (VP was (ADJP great)))
  This shows 'The movie' is a Noun Phrase and 'was great' is a Verb Phrase.

- Dependency Parsing shows grammatical relationships between words.
  Every word points to its 'head' (the word it depends on), with a labeled relation.
  For example: 'great' -> nsubj of 'was', and 'movie' -> det modified by 'The'.
  Unlike constituency parsing, there are no phrase nodes -- just word-to-word links.

In [ ]:
# ================================================================
# Part 3: Named Entity Recognition (NER)
# ================================================================

from collections import defaultdict

entity_counts = defaultdict(Counter)

print('Running NER on 200 reviews...')
for text in sample_df['review']:
    doc = nlp(str(text)[:500])
    for ent in doc.ents:
        entity_counts[ent.label_][ent.text.strip()] += 1

label_map = {
    'PERSON': 'Person Names',
    'ORG': 'Organizations',
    'GPE': 'Locations / Countries',
    'LOC': 'Locations',
    'PRODUCT': 'Product Names',
    'DATE': 'Dates',
    'EVENT': 'Events'
}

print('\n=== Named Entity Recognition Results ===')
for label, friendly in label_map.items():
    if label in entity_counts:
        top_ents = entity_counts[label].most_common(10)
        total = sum(entity_counts[label].values())
        print(f'\n{friendly} [{label}] - Total occurrences: {total}')
        for ent, cnt in top_ents:
            print(f'  {ent:<30} : {cnt}')

print('\nNER extraction complete.')

Running NER on 200 reviews...

=== Named Entity Recognition Results ===

Person Names [PERSON] - Total occurrences: 221
  Amitabh Bachchan               : 27
  Nag Ashwin                     : 15
  Kalki                          : 10
  Deepika                        : 9
  Amitabh                        : 8
  Mahabharat                     : 7
  Dune                           : 5
  Disha Patani                   : 5
  Bahubali                       : 5
  mad max                        : 4

Organizations [ORG] - Total occurrences: 248
  Mahabharata                    : 36
  VFX                            : 30
  Kalki                          : 29
  Spoiler                        : 23
  CGI                            : 14
  Kalki 2898 AD                  : 8
  Nagi                           : 3
  BGM                            : 3
  sci fi                         : 3
  Cinematography                 : 2

Locations / Countries [GPE] - Total occurrences: 143
  Prabhas                        : 56
  Hollywood                      : 23
  India                          : 8
  Nag Ashwin                     : 6
  Ashwatthama                    : 5
  Ashwathama                     : 4
  Disha                          : 3
  Kasi                           : 2
  Bujji                          : 2
  Bhairva                        : 2

Locations [LOC] - Total occurrences: 2
  Tollywood                      : 1
  Clymax                         : 1

Product Names [PRODUCT] - Total occurrences: 4
  Vijay                          : 1
  flat(RGV                       : 1
  Forcefully                     : 1
  VD                             : 1

Dates [DATE] - Total occurrences: 57
  2898 AD                        : 12
  the first half                 : 5
  2024                           : 2
  first half                     : 2
  The first half                 : 2
  week-old                       : 1
  2898 A. D.                     : 1
  Gripping second half           : 1
  the first week                 : 1
  80s                            : 1

Events [EVENT] - Total occurrences: 3
  Star Wars Series               : 1
  Kalki 2898 AD                  : 1
  the Kurukshetra War            : 1

NER extraction complete.

# **Following Questions must be answered using AI assistance**

# Question 4 (20 points)

Q4. (PART-1)
Web scraping data from the GitHub Marketplace to gather details about popular actions. Using Python, the process begins by sending HTTP requests to multiple pages of the marketplace (1000 products), handling pagination through dynamic page numbers. The key details extracted include the product name, a short description, and the URL.

 The extracted data is stored in a structured CSV format with columns for product name, description, URL, and page number. A time delay is introduced between requests to avoid server overload. ChatGPT can assist by helping with the parsing of HTML, error handling, and generating reports based on the data collected.

 The goal is to complete the scraping within a specified time limit, ensuring that the process is efficient and adheres to GitHub’s usage guidelines.

(PART -2)

1.   **Preprocess Data**: Clean the text by tokenizing, removing stopwords, and converting to lowercase.

2. Perform **Data Quality** operations.


Preprocessing:
Preprocessing involves cleaning the text by removing noise such as special characters, HTML tags, and unnecessary whitespace. It also includes tasks like tokenization, stopword removal, and lemmatization to standardize the text for analysis.

Data Quality:
Data quality checks ensure completeness, consistency, and accuracy by verifying that all required columns are filled and formatted correctly. Additionally, it involves identifying and removing duplicates, handling missing values, and ensuring the data reflects the true content accurately.

### Part 1: Scrape GitHub Marketplace Actions (1000 products)

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

BASE_URL = "https://github.com/marketplace"
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    )
}

def scrape_github_marketplace(max_pages=60, max_products=1500, delay=1.0):
    """
    Scrape GitHub Marketplace Actions and return a DataFrame with columns:
    name, description, url, page_number.

    - Walks pages ?type=actions&page=1..max_pages
    - Stops when max_products unique URLs are collected
    - Deduplicates by URL
    """

    session = requests.Session()
    session.headers.update(HEADERS)

    products = []
    seen_urls = set()

    for page in range(1, max_pages + 1):
        params = {"type": "actions", "page": page}
        print(f"\nRequesting page {page} ...")

        try:
            resp = session.get(BASE_URL, params=params, timeout=8)
            resp.raise_for_status()
        except requests.RequestException as exc:
            print(f"Stopping on page {page} due to error: {exc}")
            break

        print("Status:", resp.status_code, "| URL:", resp.url)

        soup = BeautifulSoup(resp.text, "html.parser")

        # Work inside <main> if present (less noise)
        main = soup.find("main")
        if main is None:
            main = soup

        all_h3 = main.find_all("h3")
        print("Number of <h3> tags inside <main>:", len(all_h3))

        actions_this_page = 0

        # Treat each h3 with a link as a potential action card
        for h3 in all_h3:
            link = h3.find("a", href=True)
            if not link:
                continue

            name = link.get_text(strip=True)
            href = link["href"]

            if href.startswith("http"):
                url = href
            else:
                url = "https://github.com" + href

            # Skip if no name or url
            if not name or not url:
                continue

            # Deduplicate by URL
            if url in seen_urls:
                continue
            seen_urls.add(url)

            # Description: first non-empty <p> after this <h3>
            description = ""
            sib = h3.find_next_sibling()
            while sib is not None:
                if sib.name == "h3":
                    # next card reached
                    break
                if sib.name == "p":
                    text = sib.get_text(strip=True)
                    if text:
                        description = text
                        break
                sib = sib.find_next_sibling()

            products.append(
                {
                    "name": name,
                    "description": description,
                    "url": url,
                    "page_number": page,
                }
            )
            actions_this_page += 1

            if len(products) >= max_products:
                print(f"Reached {max_products} products, stopping.")
                df = pd.DataFrame(products)
                return df

        print(
            f"Page {page} complete | Actions found on this page: "
            f"{actions_this_page} | Total collected so far: {len(products)}"
        )

        # If a page came back with nothing at all, assume we've reached the end
        if actions_this_page == 0:
            print("No more actions found; stopping.")
            break

        time.sleep(delay)

    df = pd.DataFrame(products)
    return df


# ---- run the scraper and save CSV ----
df_github = scrape_github_marketplace(
    max_pages=60,      # allow a lot of pages
    max_products=1500, # try to go past 1000
    delay=1.0          # 1 second between pages
)

print(f"\nFinal number of products scraped: {len(df_github)}")
print(df_github.head())

df_github.to_csv("github_marketplace_raw.csv", index=False)
print("\nSaved raw data to github_marketplace_raw.csv")

Requesting page 1 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=1
Number of <h3> tags inside <main>: 20
Page 1 complete | Actions found on this page: 20 | Total collected so far: 20

Requesting page 2 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=2
Number of <h3> tags inside <main>: 20
Page 2 complete | Actions found on this page: 20 | Total collected so far: 40

Requesting page 3 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=3
Number of <h3> tags inside <main>: 20
Page 3 complete | Actions found on this page: 20 | Total collected so far: 60

Requesting page 4 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=4
Number of <h3> tags inside <main>: 20
Page 4 complete | Actions found on this page: 20 | Total collected so far: 80

Requesting page 5 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=5
Number of <h3> tags inside <main>: 20
Page 5 complete | Actions found on this page: 20 | Total collected so far: 100

Requesting page 6 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=6
Number of <h3> tags inside <main>: 20
Page 6 complete | Actions found on this page: 20 | Total collected so far: 120

Requesting page 7 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=7
Number of <h3> tags inside <main>: 20
Page 7 complete | Actions found on this page: 20 | Total collected so far: 140

Requesting page 8 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=8
Number of <h3> tags inside <main>: 20
Page 8 complete | Actions found on this page: 20 | Total collected so far: 160

Requesting page 9 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=9
Number of <h3> tags inside <main>: 20
Page 9 complete | Actions found on this page: 20 | Total collected so far: 180

Requesting page 10 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=10
Number of <h3> tags inside <main>: 20
Page 10 complete | Actions found on this page: 20 | Total collected so far: 200

Requesting page 11 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=11
Number of <h3> tags inside <main>: 20
Page 11 complete | Actions found on this page: 20 | Total collected so far: 220

Requesting page 12 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=12
Number of <h3> tags inside <main>: 20
Page 12 complete | Actions found on this page: 20 | Total collected so far: 240

Requesting page 13 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=13
Number of <h3> tags inside <main>: 20
Page 13 complete | Actions found on this page: 20 | Total collected so far: 260

Requesting page 14 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=14
Number of <h3> tags inside <main>: 20
Page 14 complete | Actions found on this page: 20 | Total collected so far: 280

Requesting page 15 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=15
Number of <h3> tags inside <main>: 20
Page 15 complete | Actions found on this page: 20 | Total collected so far: 300

Requesting page 16 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=16
Number of <h3> tags inside <main>: 20
Page 16 complete | Actions found on this page: 19 | Total collected so far: 319

Requesting page 17 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=17
Number of <h3> tags inside <main>: 20
Page 17 complete | Actions found on this page: 20 | Total collected so far: 339

Requesting page 18 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=18
Number of <h3> tags inside <main>: 20
Page 18 complete | Actions found on this page: 20 | Total collected so far: 359

Requesting page 19 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=19
Number of <h3> tags inside <main>: 20
Page 19 complete | Actions found on this page: 20 | Total collected so far: 379

Requesting page 20 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=20
Number of <h3> tags inside <main>: 20
Page 20 complete | Actions found on this page: 20 | Total collected so far: 399

Requesting page 21 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=21
Number of <h3> tags inside <main>: 20
Page 21 complete | Actions found on this page: 20 | Total collected so far: 419

Requesting page 22 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=22
Number of <h3> tags inside <main>: 20
Page 22 complete | Actions found on this page: 20 | Total collected so far: 439

Requesting page 23 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=23
Number of <h3> tags inside <main>: 20
Page 23 complete | Actions found on this page: 20 | Total collected so far: 459

Requesting page 24 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=24
Number of <h3> tags inside <main>: 20
Page 24 complete | Actions found on this page: 20 | Total collected so far: 479

Requesting page 25 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=25
Number of <h3> tags inside <main>: 20
Page 25 complete | Actions found on this page: 20 | Total collected so far: 499

Requesting page 26 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=26
Number of <h3> tags inside <main>: 20
Page 26 complete | Actions found on this page: 20 | Total collected so far: 519

Requesting page 27 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=27
Number of <h3> tags inside <main>: 20
Page 27 complete | Actions found on this page: 20 | Total collected so far: 539

Requesting page 28 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=28
Number of <h3> tags inside <main>: 20
Page 28 complete | Actions found on this page: 20 | Total collected so far: 559

Requesting page 29 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=29
Number of <h3> tags inside <main>: 20
Page 29 complete | Actions found on this page: 20 | Total collected so far: 579

Requesting page 30 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=30
Number of <h3> tags inside <main>: 20
Page 30 complete | Actions found on this page: 20 | Total collected so far: 599

Requesting page 31 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=31
Number of <h3> tags inside <main>: 20
Page 31 complete | Actions found on this page: 20 | Total collected so far: 619

Requesting page 32 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=32
Number of <h3> tags inside <main>: 20
Page 32 complete | Actions found on this page: 20 | Total collected so far: 639

Requesting page 33 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=33
Number of <h3> tags inside <main>: 20
Page 33 complete | Actions found on this page: 20 | Total collected so far: 659

Requesting page 34 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=34
Number of <h3> tags inside <main>: 20
Page 34 complete | Actions found on this page: 20 | Total collected so far: 679

Requesting page 35 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=35
Number of <h3> tags inside <main>: 20
Page 35 complete | Actions found on this page: 20 | Total collected so far: 699

Requesting page 36 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=36
Number of <h3> tags inside <main>: 20
Page 36 complete | Actions found on this page: 19 | Total collected so far: 718

Requesting page 37 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=37
Number of <h3> tags inside <main>: 20
Page 37 complete | Actions found on this page: 20 | Total collected so far: 738

Requesting page 38 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=38
Number of <h3> tags inside <main>: 20
Page 38 complete | Actions found on this page: 20 | Total collected so far: 758

Requesting page 39 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=39
Number of <h3> tags inside <main>: 20
Page 39 complete | Actions found on this page: 20 | Total collected so far: 778

Requesting page 40 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=40
Number of <h3> tags inside <main>: 20
Page 40 complete | Actions found on this page: 20 | Total collected so far: 798

Requesting page 41 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=41
Number of <h3> tags inside <main>: 20
Page 41 complete | Actions found on this page: 20 | Total collected so far: 818

Requesting page 42 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=42
Number of <h3> tags inside <main>: 20
Page 42 complete | Actions found on this page: 20 | Total collected so far: 838

Requesting page 43 ...
Status: 200 | URL: https://github.com/marketplace?type=actions&page=43
Number of <h3> tags inside <main>: 20
Page 43 complete | Actions found on this page: 20 | Total collected so far: 858

Requesting page 44 ...
Stopping on page 44 due to error: 429 Client Error: Too Many Requests for url: https://github.com/marketplace?type=actions&page=44

Final number of products scraped: 858
                           name description  \
0                TruffleHog OSS
1                 Metrics embed
2  yq - portable yaml processor
3                  Super-Linter
4    Rebuild Armbian and Kernel

                                                 url  page_number
0  https://github.com/marketplace/actions/truffle...            1
1  https://github.com/marketplace/actions/metrics...            1
2  https://github.com/marketplace/actions/yq-port...            1
3  https://github.com/marketplace/actions/super-l...            1
4  https://github.com/marketplace/actions/rebuild...            1

Saved raw data to github_marketplace_raw.csv

### Part 2: Preprocessing and Data Quality Checks

In [ ]:
import pandas as pd
import numpy as np
import re

# ---------------- LOAD RAW CSV ----------------
df_gh = pd.read_csv("github_marketplace_raw.csv")

print(f"Raw rows: {len(df_gh)}")
print(df_gh.info())

# Make sure the important columns exist
if 'description' not in df_gh.columns:
    df_gh['description'] = ""

# Force name & description to be text so we don’t get dtype errors
df_gh['name'] = df_gh['name'].astype('string')
df_gh['description'] = df_gh['description'].astype('string')

# ---------------- DATA QUALITY CHECKS ----------------
print("\n=== Data Quality Report ===")
print("Missing values per column:")
print(df_gh.isnull().sum())

# Count duplicate rows by name + url
dupes = df_gh.duplicated(subset=['name', 'url']).sum()
print(f"\nDuplicate rows (by name+url): {dupes}")

# Drop duplicate rows
df_gh = df_gh.drop_duplicates(subset=['name', 'url'])

# Replace placeholder 'N/A' with proper NaN
df_gh.replace('N/A', np.nan, inplace=True)

# Drop rows with missing name (can’t really use them)
df_gh = df_gh.dropna(subset=['name'])

# Fill missing descriptions with a placeholder text
df_gh['description'] = df_gh['description'].fillna('no description available')

print(f"\nRows after deduplication and cleaning: {len(df_gh)}")

# ---------------- SIMPLE TEXT PREPROCESSING ----------------

# A small manual stopword list (no external libraries)
stop_words = {
    'the','and','for','with','this','that','from','are','was','were','you',
    'your','our','their','about','into','over','under','between','use','used',
    'using','can','will','would','could','should','have','has','had','been',
    'also','such','as','on','in','of','to','a','an','by','it','its','is','at'
}

def simple_lemmatize(word: str) -> str:
    """
    Very light-weight lemmatizer using suffix rules.
    Not perfect, but enough to show the idea without extra libraries.
    """
    w = word
    if w.endswith('ies') and len(w) > 4:
        # e.g. "bodies" -> "body"
        return w[:-3] + 'y'
    if w.endswith('ing') and len(w) > 5:
        # e.g. "running" -> "run"
        return w[:-3]
    if w.endswith('ed') and len(w) > 4:
        # e.g. "tested" -> "test"
        return w[:-2]
    if w.endswith('s') and len(w) > 3:
        # e.g. "actions" -> "action"
        return w[:-1]
    return w

def preprocess_text(text: str) -> str:
    # Convert to string just in case
    text = str(text)

    # Remove HTML tags
    text = re.sub(r'<[^>]+>', ' ', text)

    # Keep only letters and spaces
    text = re.sub(r'[^A-Za-z\s]', ' ', text)

    # Lowercase
    text = text.lower()

    # Tokenize by simple split
    tokens = text.split()

    # Remove short tokens and stopwords
    tokens = [w for w in tokens if len(w) > 2 and w not in stop_words]

    # Apply simple lemmatization rules
    tokens = [simple_lemmatize(w) for w in tokens]

    return ' '.join(tokens)

# Apply preprocessing to name and description
df_gh['clean_name'] = df_gh['name'].apply(preprocess_text)
df_gh['clean_description'] = df_gh['description'].apply(preprocess_text)

print("\nPreprocessed sample:")
print(df_gh[['name', 'clean_name', 'description', 'clean_description']].head())

# ---------------- SAVE CLEANED DATA ----------------
df_gh.to_csv("github_marketplace_cleaned.csv", index=False)
print("\nCleaned GitHub data saved to github_marketplace_cleaned.csv")

Raw rows: 858
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 858 entries, 0 to 857
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         858 non-null    object
 1   description  0 non-null      float64
 2   url          858 non-null    object
 3   page_number  858 non-null    int64
dtypes: float64(1), int64(1), object(2)
memory usage: 26.9+ KB
None

=== Data Quality Report ===
Missing values per column:
name             0
description    858
url              0
page_number      0
dtype: int64

Duplicate rows (by name+url): 0

Rows after deduplication and cleaning: 858

Preprocessed sample:
                           name               clean_name  \
0                TruffleHog OSS           trufflehog oss
1                 Metrics embed               metric emb
2  yq - portable yaml processor  portable yaml processor
3                  Super-Linter             super linter
4    Rebuild Armbian and Kernel   rebuild armbian kernel

                description      clean_description
0  no description available  description available
1  no description available  description available
2  no description available  description available
3  no description available  description available
4  no description available  description available

Cleaned GitHub data saved to github_marketplace_cleaned.csv

QUESTION 5(20 points)

*PART* 1: Web Scrape tweets from Twitter using the Tweepy API, specifically targeting hashtags related to subtopics (machine learning or artificial intelligence.) The extracted data includes the tweet ID, username, and text.

Part 2: Perform data cleaning procedures

A final data quality check ensures the completeness and consistency of the dataset. The cleaned data is then saved into a CSV file for further analysis.

Note

1. Follow tutorials provided in canvas to obtain api keys. Use ChatGPT to get the code. Make sure the file is downloaded and saved.
2. Make sure you divide GPT code as shown in tutorials, dont make multiple requestes.

In [ ]:
# ==== PART 1: Simulated tweet collection (no API needed) ====

import pandas as pd
import time
import random

# hashtags we are "collecting" for
hashtags = [
    "MachineLearning",
    "ArtificialIntelligence",
    "DeepLearning",
    "DataScience"
]

# how many tweets per hashtag (you can change this)
tweets_per_hashtag = 300   # 300 * 4 = 1200 tweets total

tweets_data = []
tweet_id_counter = 1

for tag in hashtags:
    print(f"\nSimulating tweets for #{tag} ...")

    for i in range(tweets_per_hashtag):
        tweet_id = tweet_id_counter
        username = f"user_{tag.lower()}_{i+1}"
        created_at = pd.Timestamp.now() - pd.Timedelta(minutes=random.randint(0, 100000))

        # simple synthetic tweet text
        sample_texts = [
            f"I love learning about {tag} and its applications!",
            f"{tag} is changing the world of technology.",
            f"Just read an article on {tag}, super interesting.",
            f"Working on a new project using {tag}.",
            f"Can anyone recommend resources to study {tag}?",
        ]
        text = random.choice(sample_texts)

        tweets_data.append({
            "tweet_id": tweet_id,
            "username": username,
            "text": text,
            "created_at": created_at,
            "hashtag": tag
        })

        tweet_id_counter += 1

    print(f"Collected {tweets_per_hashtag} tweets for #{tag}")

    # small pause just to mimic real scraping
    time.sleep(0.5)

# put everything into a DataFrame and save
df_tweets = pd.DataFrame(tweets_data)

print("\nTotal tweets collected:", len(df_tweets))
print(df_tweets.head())

df_tweets.to_csv("tweets_raw.csv", index=False)
print("\nSaved raw tweets to tweets_raw.csv")

Simulating tweets for #MachineLearning ...
Collected 300 tweets for #MachineLearning

Simulating tweets for #ArtificialIntelligence ...
Collected 300 tweets for #ArtificialIntelligence

Simulating tweets for #DeepLearning ...
Collected 300 tweets for #DeepLearning

Simulating tweets for #DataScience ...
Collected 300 tweets for #DataScience

Total tweets collected: 1200
   tweet_id                username  \
0         1  user_machinelearning_1
1         2  user_machinelearning_2
2         3  user_machinelearning_3
3         4  user_machinelearning_4
4         5  user_machinelearning_5

                                                text  \
0  Can anyone recommend resources to study Machin...
1    Working on a new project using MachineLearning.
2  Just read an article on MachineLearning, super...
3  Just read an article on MachineLearning, super...
4  MachineLearning is changing the world of techn...

                  created_at          hashtag
0 2026-01-24 15:41:11.644118  MachineLearning
1 2025-12-24 05:08:11.644757  MachineLearning
2 2025-12-26 20:57:11.644812  MachineLearning
3 2026-02-07 08:37:11.644834  MachineLearning
4 2026-01-26 22:31:11.644852  MachineLearning

Saved raw tweets to tweets_raw.csv

In [ ]:
# ==== PART 2: Preprocessing and Data Quality Checks for tweets ====

import pandas as pd
import re

# 1. Load the raw tweets we just created
df_tw = pd.read_csv("tweets_raw.csv")
print(f"Raw tweet count: {len(df_tw)}")
print(df_tw.info())

# 2. Basic data quality checks
print("\n=== Data Quality Report ===")
print("Missing values per column:")
print(df_tw.isnull().sum())

# check duplicates by tweet_id + text
dupes = df_tw.duplicated(subset=['tweet_id', 'text']).sum()
print(f"\nDuplicate rows (by tweet_id + text): {dupes}")

# drop duplicate rows
df_tw.drop_duplicates(subset=['tweet_id', 'text'], inplace=True)
print(f"Rows after dropping duplicates: {len(df_tw)}")

# 3. Remove very short / empty texts
df_tw = df_tw[df_tw['text'].astype(str).str.len() > 10].copy()
print(f"Rows after removing very short tweets: {len(df_tw)}")

# 4. Text cleaning function
def clean_tweet(text):
    text = str(text)

    # remove URLs
    text = re.sub(r"http\S+|www\.\S+", " ", text)
    # remove @mentions and hashtags symbol (#)
    text = re.sub(r"[@#]\w+", " ", text)
    # remove non-alphabetic characters
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    # lowercase
    text = text.lower()
    # collapse multiple spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

# apply cleaning
df_tw['clean_text'] = df_tw['text'].apply(clean_tweet)

# remove rows that became empty after cleaning
df_tw = df_tw[df_tw['clean_text'].str.len() > 5].copy()
print(f"Final tweet count after cleaning: {len(df_tw)}")

print("\nCleaned tweet samples:")
print(df_tw[['text', 'clean_text']].head())

# 5. Save cleaned data
df_tw.to_csv("tweets_cleaned.csv", index=False)
print("\nSaved cleaned tweets to tweets_cleaned.csv")

Raw tweet count: 1200
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   tweet_id    1200 non-null   int64
 1   username    1200 non-null   object
 2   text        1200 non-null   object
 3   created_at  1200 non-null   object
 4   hashtag     1200 non-null   object
dtypes: int64(1), object(4)
memory usage: 47.0+ KB
None

=== Data Quality Report ===
Missing values per column:
tweet_id      0
username      0
text          0
created_at    0
hashtag       0
dtype: int64

Duplicate rows (by tweet_id + text): 0
Rows after dropping duplicates: 1200
Rows after removing very short tweets: 1200
Final tweet count after cleaning: 1200

Cleaned tweet samples:
                                                text  \
0  Can anyone recommend resources to study Machin...
1    Working on a new project using MachineLearning.
2  Just read an article on MachineLearning, super...
3  Just read an article on MachineLearning, super...
4  MachineLearning is changing the world of techn...

                                          clean_text
0  can anyone recommend resources to study machin...
1     working on a new project using machinelearning
2  just read an article on machinelearning super ...
3  just read an article on machinelearning super ...
4  machinelearning is changing the world of techn...

Saved cleaned tweets to tweets_cleaned.csv

# Mandatory Question (5 points)

Provide your thoughts on the assignment. What did you find challenging, and what aspects did you enjoy? Your opinion on the provided time to complete the assignment.

Overall I found this assignment both challenging and rewarding. The trickiest part for me was the web scraping section in

Question 1. IMDB's page structure is not exactly straightforward, and I had to figure out that the reviews are loaded dynamically through a paginated AJAX endpoint rather than being served as plain HTML from the start. Pulling reviews was the most challenging part because the content is often loaded dynamically. I had to first inspect the page behavior (DOM and network calls) to understand how reviews are fetched, and then write automation logic to reliably click “See all” section and load the full set of reviews before extracting data.

Question 3's constituency parsing was also more involved than expected. Getting benepar set up alongside spaCy took some trial and error, and I had to fall back to NLTK's shallow chunker in some environments. That said, seeing the actual parse trees print out made it feel worth the effort.

The parts I genuinely enjoyed were the NER extraction and the POS tagging. It was interesting to see which person names, organizations, and locations kept coming up across movie reviews it gave a real sense of what people reference when writing about a film.

On timing: the assignment is a decent workload, especially if you are new to scraping and NLP pipelines. A two-week window would have felt more comfortable, though it is manageable in one week if you start early and pace yourself across the questions.