<a href="https://colab.research.google.com/github/AnuBolishetty/Anubolishetty_INFO5731_Spring2026/blob/main/In_Class_Exercise_Combined_ipynb_(1)_(1)_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In-Class Exercise: Sentiment Analysis + Text Classification + Prompt Engineering

**Course:** NLP / Text Mining  
**Total Points:** 30  
**Suggested Time:** about 45 minutes total  
**Dataset:** `sentiment_classification_combined_data.csv`

**Instructions**
- Complete all questions in this notebook.
- Run all cells before submission.
- Keep your answers clear and organized.
- For the prompt engineering part, you do **not** need an API key.

## Part A — Sentiment Analysis with VADER (10 points)
In this part, use **VADER** to compute sentiment scores for the text data.

In [1]:
# Upload the dataset file from your computer (Google Colab)
from google.colab import files

uploaded = files.upload()
filename = next(iter(uploaded))
print("Uploaded file name:", filename)

Saving sentiment_classification_combined_data.csv to sentiment_classification_combined_data.csv
Uploaded file name: sentiment_classification_combined_data.csv

### Q1. Load and inspect the dataset (2 points)
Show:
1. the first 5 rows  
2. the shape of the dataset  
3. the column names

In [2]:
# Read the uploaded CSV file
import pandas as pd

df = pd.read_csv(filename)
...
# First 5 rows
print(df.head())

# Shape of dataset
print("Shape:", df.shape)

# Column names
print("Columns:", df.columns)

                                                Text TrueLabel  Score
0  I loved this healthcare AI workshop. The examp...  positive      5
1  This lecture was okay, but some parts were con...   neutral      3
2  The notebook was easy to follow and very pract...  positive      5
3  I did not like the explanation of the model re...  negative      1
4  The activity was interesting and helped me und...  positive      4
Shape: (24, 3)
Columns: Index(['Text', 'TrueLabel', 'Score'], dtype='object')

### Q2. Apply VADER to compute sentiment scores (3 points)
- Import VADER
- Download the lexicon if needed
- Create a new column called `compound`
- Show the first 5 rows of `Text` and `compound`

In [3]:
!pip -q install nltk
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

In [4]:
from nltk.sentiment import SentimentIntensityAnalyzer

sia = SentimentIntensityAnalyzer()

# Compute compound sentiment score
df["compound"] = df["Text"].apply(lambda x: sia.polarity_scores(str(x))["compound"])

# Show first 5 rows
df[["Text", "compound"]].head()

                                                Text  compound
0  I loved this healthcare AI workshop. The examp...    0.8555
1  This lecture was okay, but some parts were con...   -0.2263
2  The notebook was easy to follow and very pract...    0.4404
3  I did not like the explanation of the model re...   -0.2755
4  The activity was interesting and helped me und...    0.4019

### Q3. Create a sentiment label from the compound score (3 points)
Create a new column called `PredictedSentiment` using this rule:
- `compound >= 0.05` → `positive`
- `compound <= -0.05` → `negative`
- otherwise → `neutral`

Then show the first 10 rows of `Text`, `compound`, and `PredictedSentiment`.

In [5]:
def get_sentiment(score):
    if score >= 0.05:
        return "positive"
    elif score <= -0.05:
        return "negative"
    else:
        return "neutral"

df["PredictedSentiment"] = df["compound"].apply(get_sentiment)

# Show first 10 rows
df[["Text", "compound", "PredictedSentiment"]].head(10)

,Text,compound,PredictedSentiment
0,I loved this healthcare AI workshop. The examp...,0.8555,positive
1,"This lecture was okay, but some parts were con...",-0.2263,negative
2,The notebook was easy to follow and very pract...,0.4404,positive
3,I did not like the explanation of the model re...,-0.2755,negative
4,The activity was interesting and helped me und...,0.4019,positive
5,The class was too fast and I could not follow ...,0.0000,neutral
6,"The topic is important, but the instructions w...",0.1027,positive
7,I really enjoyed the examples and the live cod...,0.5563,positive
8,The dataset was messy and the task felt frustr...,-0.6597,negative
9,The exercise was manageable and useful for pra...,0.4404,positive

### Q4. Compare review score and sentiment (2 points)
Group by `Score` and compute the **average compound score** for each score value.

In [8]:
df.groupby("Score")["compound"].mean()

Score
1   -0.507033
2   -0.296125
3   -0.150783
4    0.478340
5    0.621167
Name: compound, dtype: float64

## Part B — Prompt Engineering (10 points)
This part is based on the **Prompt Engineering** notebook. You do **not** need an API key. Focus on writing better prompts using the concepts of **instruction, context, output format, zero-shot, few-shot, and chain-of-thought**.

In [9]:
# Sample texts for the prompt engineering questions
sample_reviews = [
    "The product arrived late and the quality was poor.",
    "Amazing battery life and elegant design.",
    "It is fine for daily use, nothing special."
]
for i, text in enumerate(sample_reviews, start=1):
    print(f"{i}. {text}")

1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.

### Q1. Zero-shot classification prompt (3 points)
Write a **zero-shot prompt** that asks an AI model to classify each review as **positive, negative, or neutral**.

Your prompt should include:
- a clear instruction
- the three labels
- a request for a clean output format

Store your prompt in a Python variable called `zero_shot_prompt`, then print it.

In [10]:
zero_shot_prompt = """
Classify each review into one of the following categories: positive, negative, neutral.

Labels:
- positive: positive sentiment
- negative: negative sentiment
- neutral: mixed or no clear sentiment

Instructions:
Return only the label for each review in a clean list format.

Reviews:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.
"""

print(zero_shot_prompt)

Classify each review into one of the following categories: positive, negative, neutral.

Labels:
- positive: positive sentiment
- negative: negative sentiment
- neutral: mixed or no clear sentiment

Instructions:
Return only the label for each review in a clean list format.

Reviews:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.

### Q2. Few-shot prompt improvement (3 points)
Now improve the previous prompt by adding **two examples**.

Requirements:
- Store it in a variable called `few_shot_prompt`
- Include 2 input-output examples
- Ask the model to classify the 3 sample reviews after the examples

In [11]:
few_shot_prompt = """
Classify reviews as positive, negative, or neutral.

Examples:

Review: I love this product, it works perfectly.
Sentiment: positive

Review: This is the worst purchase I have ever made.
Sentiment: negative


Now classify the following reviews:

1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.

Return only the sentiment labels.
"""

print(few_shot_prompt)

Classify reviews as positive, negative, or neutral.

Examples:

Review: I love this product, it works perfectly.
Sentiment: positive

Review: This is the worst purchase I have ever made.
Sentiment: negative


Now classify the following reviews:

1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.

Return only the sentiment labels.

### Q3. Prompt comparison and refinement (4 points)
Create a short table or DataFrame with **three columns**:
- `PromptType`
- `MainFeature`
- `WhyUseful`

Include these three prompt types:
1. Zero-shot
2. Few-shot
3. Chain-of-thought

Then, in **2–3 sentences**, explain which one you would choose for a more difficult text analysis task and why.

In [12]:
import pandas as pd

data = {
    "PromptType": ["Zero-shot", "Few-shot", "Chain-of-thought"],
    "MainFeature": [
        "No examples, direct instruction",
        "Includes labeled examples",
        "Encourages step-by-step reasoning"
    ],
    "WhyUseful": [
        "Fast and simple for basic tasks",
        "Improves accuracy using patterns",
        "Best for complex reasoning and ambiguity"
    ]
}

df_prompts = pd.DataFrame(data)
df_prompts

,PromptType,MainFeature,WhyUseful
0,Zero-shot,"No examples, direct instruction",Fast and simple for basic tasks
1,Few-shot,Includes labeled examples,Improves accuracy using patterns
2,Chain-of-thought,Encourages step-by-step reasoning,Best for complex reasoning and ambiguity

Few-shot prompting tends to be the most accurate when performing practical sentiment tasks due to the clear instances provided to the model to adhere to. However, when using more challenging or uncertain text analysis problems, chain-of-thought prompting tends to be more effective as it compels the model to think step-by -step before making the final label, enhancing accuracy.

## Reflection (optional, no extra points)
Briefly explain the difference between:
- sentiment analysis
- text classification
- prompt engineering